/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class waffleoRai_MediaAdapter_audio_FLACEncoder */

#ifndef _Included_waffleoRai_MediaAdapter_audio_FLACEncoder
#define _Included_waffleoRai_MediaAdapter_audio_FLACEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    openStream
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_openStream__Ljava_lang_String_2III
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    openStream
 * Signature: (Ljava/lang/String;IIII)J
 */
JNIEXPORT jlong JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_openStream__Ljava_lang_String_2IIII
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    getSamplesPerBlock
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_getSamplesPerBlock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    passSamples
 * Signature: (J[II)I
 */
JNIEXPORT jint JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_passSamples
  (JNIEnv *, jobject, jlong, jintArray, jint);

/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    closeStream
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_closeStream
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
