/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include "vp9Adapter.h"
/* Header for class waffleoRai_MediaAdapter_video_VP9Encoder */

#ifndef _Included_waffleoRai_MediaAdapter_video_VP9Encoder
#define _Included_waffleoRai_MediaAdapter_video_VP9Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     waffleoRai_MediaAdapter_video_VP9Encoder
 * Method:    openLosslessStream
 * Signature: (Ljava/lang/String;IIIII)J
 */
JNIEXPORT jlong JNICALL Java_waffleoRai_1MediaAdapter_video_VP9Encoder_openLosslessStream
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     waffleoRai_MediaAdapter_video_VP9Encoder
 * Method:    openLossyStream
 * Signature: (Ljava/lang/String;IIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_waffleoRai_1MediaAdapter_video_VP9Encoder_openLossyStream
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     waffleoRai_MediaAdapter_video_VP9Encoder
 * Method:    setCallbackTime
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_waffleoRai_1MediaAdapter_video_VP9Encoder_setCallbackTime
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     waffleoRai_MediaAdapter_video_VP9Encoder
 * Method:    writeFrame
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_waffleoRai_1MediaAdapter_video_VP9Encoder_writeFrame
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     waffleoRai_MediaAdapter_video_VP9Encoder
 * Method:    writeFrames
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_waffleoRai_1MediaAdapter_video_VP9Encoder_writeFrames
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     waffleoRai_MediaAdapter_video_VP9Encoder
 * Method:    closeStream
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_waffleoRai_1MediaAdapter_video_VP9Encoder_closeStream
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
