/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class waffleoRai_MediaAdapter_audio_FLACEncoder */

#ifndef _Included_waffleoRai_MediaAdapter_audio_FLACEncoder
#define _Included_waffleoRai_MediaAdapter_audio_FLACEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    openStream
 * Signature: (Ljava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_openStream
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    getSamplesPerBlock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_getSamplesPerBlock
  (JNIEnv *, jobject);

/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    passSamples
 * Signature: ([[II)Z
 */
JNIEXPORT jboolean JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_passSamples
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     waffleoRai_MediaAdapter_audio_FLACEncoder
 * Method:    closeStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_waffleoRai_1MediaAdapter_audio_FLACEncoder_closeStream
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
